import type {Metadata} from "next";
import "@/styles/globals.css";
import {Header} from "@/sections/Header";
import {Footer} from "@/sections/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
        <body className="h-dvh bg-secondary">
        <Header/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
