import type {Metadata, Viewport} from "next";
import "@/styles/globals.css";
import {Header} from "@/sections/Header";
import {Footer} from "@/sections/Footer";
import {UserProvider} from "@auth0/nextjs-auth0/client";
import {QueryWrapper} from "@/components/QueryWrapper";

export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export const viewport: Viewport = {
    initialScale: 1, maximumScale: 1, width: 'device-width', userScalable: false,
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (<html lang="es">
    <QueryWrapper>
        <UserProvider>
            <body className="h-dvh bg-secondary">
            <Header/>
            {children}
            <Footer/>
            </body>
        </UserProvider>
    </QueryWrapper>
    </html>);
}
